# docker-compose.yml

version: '3.8'
services:
  test:
    build:
      context: .
      target: test
    command: npm test

  lint:
    build:
      context: .
      target: test
    command: npm run lint

  coverage:
    build:
      context: .
      target: test
    command: npm run test:coverage
