# docker-compose.yml

services:
  test:
    build:
      context: ..
      target: test
    command: npm test

  lint:
    build:
      context: ..
      target: test
    command: npm run lint

  coverage:
    build:
      context: ..
      target: test
    command: npm run test:coverage

  e2e:
    build:
      context: ..
      target: e2e
    command: npm run test:e2e
